### ISSUE TITLE
Spin.py: unable to find device 'Watcom ISDv4 EC Pen Stylus'

### ISSUE THREAD

**Issue by venik212** [wdbm/spin#15]
I love Spin.py-- it is ALMOST what I was looking for.  However, when I run it on my Yoga 2 Pro (i7) under Lubuntu 17.10, I get a repeated error message:  unable to find device 'Watcom ISDv4 EC Pen Stylus'
The utility seems to work fine on my machine, but that error message is annoying.  I tried to run it in silent mode (spin.py -s) but that made no difference. 
I also tried to click "stylus proximity monitoring off" and "nipple off" but neither helped.
I gather that my hardware is a little different from the HW used by the developers, but is there anything I can do to tame it?
Thanks--

**Comment by wdbm** [comment]
Hey there, I'm glad you like it. This script was written with ThinkPads in mind and it appears you're seeing this error message because your device does not have a stylus, with the error message being produced by the `xinput` program. I can look at adding the capability to turn off stylus things when I have time. For now you can run the program in the background or send its terminal output to null. Please provide me with the output of the following command:

```Bash
xinput --list
```
